In [7]:
# Outside imports
import os, sys
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Set necessary paths / make project path = ...../neuroscikit/
avg_spike_width_path = os.getcwd()
prototype_path = os.path.abspath(os.path.join(avg_spike_width_path, os.pardir))
project_path = os.path.abspath(os.path.join(prototype_path, os.pardir))
lab_path = os.path.abspath(os.path.join(project_path, os.pardir))
sys.path.append(project_path)
os.chdir(project_path)
print(project_path)

# Internal imports
from _prototypes.average_spike_width.src.spike_width import extract_average_spike_widths
from _prototypes.average_spike_width.src.settings import settings_dict

# Read write modules
from x_io.rw.axona.batch_read import make_study

k:\ke

In [2]:
data_dir = lab_path + r'\neuroscikit_test_data\axona'
output_dir = lab_path + r'\neuroscikit\_prototypes\average_spike_width\output'
print(data_dir)
print(output_dir)

k:\ke\dev\neuroscikit_test_data\axona
k:\ke\dev\neuroscikit\_prototypes\average_spike_width\output

In [3]:
study = make_study([data_dir], settings_dict)
study.make_animals()

k:\ke\dev\neuroscikit\library\study_space.py:44: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  dir_names = np.array([x[1] for x in os.walk('library')])[0]

Animal ID set
Animal ID set
Session data added, spikes sorted by cell
Session data added, spikes sorted by cell

In [4]:
output_dict = extract_average_spike_widths(study)

In [5]:
pd.DataFrame(output_dict)

     animal_id      session_signature  unit_id  spike_width  firing_rate
0   axona_tet1  20140815-behavior2-90        1         0.46    23.289462
1   axona_tet1  20140815-behavior2-90        2         0.42     1.108662
2   axona_tet1  20140815-behavior2-90        3         0.44     0.251539
3   axona_tet1  20140815-behavior2-90        4         0.42     1.469883
4   axona_tet1  20140815-behavior2-90        5         0.44    21.760173
5   axona_tet1  20140815-behavior2-90        6         0.46     4.204633
6   axona_tet1  20140815-behavior2-90        7         0.46     6.126191
7   axona_tet1  20140815-behavior2-90        8         0.44    11.204727
8   axona_tet1  20140815-behavior2-90        9         0.44     1.922465
9   axona_tet1  20140815-behavior2-90       10         0.10     2.404056
10  axona_tet1  20140815-behavior2-90       11         0.40     8.124101
11  axona_tet1  20140815-behavior2-90       12         0.42     0.166500
12  axona_tet1  20140815-behavior2-90       13         0.44     1.183093
13  axona_tet1  20140815-behavior2-90       14         0.46    23.660316
14  axona_tet1  20140815-behavior2-90       15         0.10     0.555168
15  axona_tet1  20140815-behavior2-90       16         0.44     1.819072
16  axona_tet1  20140815-behavior2-90       17         0.36     2.219014
17  axona_tet1                   test        0         0.60   110.019685
18  axona_tet1                   test        1         0.18     8.334100
19  axona_tet1                   test        2         0.18     0.145274
20  axona_tet1                   test        3         0.54     2.246487
21  axona_tet1                   test        4         0.46     1.087083
22  axona_tet1                   test        5         0.48     0.779172
23  axona_tet1                   test        6         0.28     0.195551
24  axona_tet1                   test        7         0.32     0.229661
25  axona_tet1                   test        8         0.18     3.351871
26  axona_tet1                   test        9         0.14     5.623088
27  axona_tet1                   test       11         0.34     0.679945

In [6]:
pd.DataFrame(output_dict).to_csv(output_dir + r'\spike_widths.csv')